### ISSUE TITLE
Using code & more from andOTP without giving credits to it?

### ISSUE THREAD

**Issue by IzzySoft** [gigabytedevelopers/CometOTP#1]
@enwokoma just curious, did you by chance get some inspiration from [andOTP](https://github.com/andOTP/andOTP)? Several code passages look almost identical, but I don't see it mentioned on the "front page" – which besides also is almost identical to andOTP's, including complete paragraphs.

That would be the second time now, after FireFiles. Do you think that's decent? The first time I thought it was a mistake, and you had learned from it. Now, it doesn't look that way. It rather raises the question which of your other projects are genuine (sorry for being so direct, but I'm massively disappointed).

**Comment by enwokoma** [comment]
Check the About page. It was referenced there!

**Comment by enwokoma** [comment]
Plus there are numerous couple of reasons why we no longer bothered giving attribution. 
1. This project has been updated numerous times, we just haven't made the update to github
2. On this new updates, we have made a lot modifications that one can say this project is no longer built on the codebase of andOTP
3. The current look and feel of CometOTP is in no way similar to that of andOTP, everything revolves around the fact that we haven't recently made these changes to effect on this repo.
4. We already made reference of Jakob within the About Page of CometOTP

So, please, sometimes when looking into repositories, you should consider checking the end product (in this case, installing the app) before jumping into making false attribution claims, even andOTP was built off the codebase of [this](https://github.com/0xbb/otp-authenticator) but because of the numerous work they have done without any reference to Bruno, that gives Jakob enough reason not to reference Bruno but he did! This is the same situation as CometOTP, there is enough reason not to reference either Bruno not Jakob, but we did (in the About Page).

**Comment by IzzySoft** [comment]
> was built off the codebase of [this](https://github.com/0xbb/otp-authenticator) but because of the numerous work they have done without any reference to Bruno,

Both is mentioned in their README.md:

> This project started out as a fork of the great OTP Authenticator app written by Bruno Bierbaumer, …

1. andOTP has been updated a lot since then as well, still gives credit.
2. many places are literal copy-pastes (and checking the commit history, it has been copy-pasted "piece-wise"), up to now. Just compare the README.md and the Entry.java file in the database directory.
3. the look and feel has nothing to do with it. You might have changed that, or built your own, but still many parts of code are copy-pasted from there. Which is legit, given the license – but should be credited. Instead all you did again is leaving the copyright/credit headers off.

I won't discuss this again, Emmanuel – we've had that in the past with FireFiles. I'm just not happy with this.

**Comment by enwokoma** [comment]
Those headers and README were removed on purpose because we had no plans of continuing on this path (continue building off andOTP), we could even just delete this repo all together because after all, it's not even needed but no! We ain't doing that! 

So, including the headers and updating the README solves all this misunderstandings right? 
😏 😏 😏 
Sure! I would be making commits by the end of the day, but be aware that this repo might not exist after this! 

Thanks for your understanding!

**Comment by enwokoma** [comment]
I guess the best I can do in this situation is renaming the current [CometOTP](github.com/gigabytedevelopers/CometOTP) project from **CometOTP** to **CometOTP (andOTP)**, we could just delete the repo and make a fresh fork of the current andOTP project, where I would then add a reference that says _this fork was made for a onetime reference purpose only which was used for the development of CometOTP_ then make a totally new repo for CometOTP which doesn't reference andOTP because with this recent development, I guess  I am left with no option but to stripe the entire codebase of CometOTP and make it Closed-Source 

Tell me what you think about this.

**Comment by enwokoma** [comment]
I guess this commit settles it all. 

Thanks!

**Comment by IzzySoft** [comment]
Thanks also in this place for fixing it as fast!
